apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TXpBdwpNRE0xTXpSYUZ3MDBNekF4TXpBd01ETTFNelJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEMmxBYW94QlcyWkRxNU5PYXN5Z1J4Ujg2MitSNTdYdE9NMWxOd2NSR0cwc2Y2ZC90bgplUlM5d0cwL0tQUzVMUG14RUl5TGVkeFQzNllYUVhyY1lBUEh4dTg4MlRCMTVraE5CbEk5ZStkVFgyWnVFT3VsCkNNNUpkaHBNWWx2QXdKY1FJbS9CN3VrSVRTd3Nza2NwUi92T0ZOWXRiYWN0R2IyV1owK3UwcWg5Vk1raE5mYWgKaTlYVzNXODNSVlJPMDc2VGU0M0hGL1ZZcDdmQnJwd2dOeFFINGt2YThCc1NqRFhXaEVWNjk1d1MvajZBZWlIaQpYeTQ4TmFiRW15bER3V083dHBHRUQwWE5VQ2h0bkdyVWZqTHhJZ3BRTHJQOWpNejc5a3ZGVGJOc0ZPemhtTEZPCm94bVB1V1BELy9oQzk1dU5seVVIc0lOOWNHZlV0SjBCaTZZekFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlM1M1BCR3E2N3pyZm9ycEhtVAoydmRLa1lGaUxUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYSlhGMGJkaE5lbGdON1BmVklXdXZSRDlLcTRSCjNLbVQvZHl5RUFtVVJZSlFnVjhvdWMwKzJWcEVEWFlORkFKd2k2aElVemtreGFaYXBaSjBzVWZrVHIwQThKMHMKK3MzdHdZaWtKMk5QS2ZBMWxhQkFwcWFlYVdpaVdndTlZNFVRSTZ1dm5taXc3Y2IraW5OSW9jaFpRV2hENFc0awpqaSt1QUkwZDNhVzN2VVhWcGU5Q0l0YnM3YVZUb1FhSnYvUDBQbnErSjR0YkIyeXJIMXAraFd4bjJLdnRldnVBCnpQdCtpVE1FOCtKeDVqck0yejlQV05iRUk0T2ZOTi83UXluclE0V1gycDhoUS9VVEM1ZGY3Yit6d2xUbmt4SGgKTzV5TU9FMnFFUmdwZXdpc2N6NnRONDRtRGhvSk9tM0lPbm8xVHlDQUtPSWY3cUd1K3hTdllLV3kyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f05c839c-a7bf-43ab-a0d5-a09d278407e1.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_d55689a32cde43b1e2ef704f32f982535e0e9582df759e53572d003bcda84fe0
