apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreApOekl4TVRSYUZ3MDBNekF4TWpreE56SXhNVFJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDejFtazRmWlVBTEZGTTlzNUZxUUdVdzhnNVhrU1plbDdIbUI2ci9mRUF3VHZ4SFU4bgpISEhmc2FwN2RTRkxLTk1hdDJHUm8rRnFxVXFpdWk1QXgwb1ZhbW5JTmMyZS9jNzFBNThHcERSQUc1b1NvZmZzCkJjMWVzWWVwNG5DaFlsWm9KTGhXN0x0TkFvU2pBSDV0WnFJVmtsYWkrUko5bmpzVVRDbGNweGtiWXB1RWNEN3AKNzU3b24xVzdQL2NlUktGS1pzUE4vTjBJK01PYW9lRmpFRkMrQXcvWUJRdVlONUJOQ0lmTmVkMlBrWU5uRVZzWgo0UjF3T1htVFpTUVlVL3BJVE04V3V4YXdCajJwKzBCV2ZvNzRab0JBMW1NSGJQeUxCWU5qNDMvaWxjUTErM0w0Cng4YS8weExHWDNHRlc2WHoydk1udGcwTlFXeGdxdzhUZFJuL0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNDSk9xV2MyWEJpQmJpejhJMgpkSnA5YXBXQ3J6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMeG1pK3o2OVBmb3Z1d2NISW0yWFFRVktRalFOCjVNYXYvNWZ0TFZuT2hlVVZmVlhNQWZqZWwxbHhOZ09uZ0xlNHl1QVYwUkxML3AxcVI2WVAzaUo1Z3YrbzlzeHcKVG1WeDRqWkhuU1FEU0FUN2VpM2xxMFpQcWpFQWNzblZmUWVFY3VwZzRaU1EvRkQ2Ky9ZV1JnZmVmTzcrR0ZobQovU1F3cmxoZWFYTzkyK3BVRGt1cDZJL3FOTElVNTg5RDZMYkJuUTBHQW92bmcwVnlNVC9QMVl3QStRL21CRGR2Cmx2RVNmQXlEazh2ZkpwVkpIVE9DL0NHWDRBQ2kxb0hjZHhKNmV1UXdNdjNZK3lXUFJOeEh6eERyNEQybWk4cXIKaWREckxJSElZSFdORXhRMlZnc3pqSHRDWFBvcEpYczd0YVV4LzV2MWpkbGtQNFRIWkZsTXRVcHZ5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://bfcffd1b-5edb-4e7e-a781-52d392667287.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_aef87a797e90e189d0db5c9b39bae8ceb47e4b282120f7d0ab7f5ad8f8c3752c
